# fly.toml app configuration file for edge-proxy--zhz-w

app = "edge-proxy--zhz-w"
primary_region = "gru"

[build]
  dockerfile = "Dockerfile"   # <- força usar teu Dockerfile

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
